### PR TITLE
fix: Update list of deprecated libs

### PR DESCRIPTION
**Pull request by matz3**
- Sort entries
- Remove non-existent sap.dragonfly
- Fix typo for sap.landvisz
- Add missing sap.sac.grid

### CODE REVIEW

**Comment by codeworrior** [comment]
Sorry, I think I had mixed up sap.sac.df (dragonfly - still exists) and sap.sac.grid (deprecated and removed after 1.113)

**Review by codeworrior — APPROVED** [review]
LGTM

**Review by codeworrior — APPROVED** [review]
I can't judge whether the 2 bytes in the snapshot file are okay, but otherwise the change LGTM.

**Comment by RandomByte** [comment]
What about `sap.fe.common` and `sap.fe.semantics` (both removed after 1.108 and 1.102 respectively)?

**Review by RandomByte — APPROVED** [review]

**Pull request merged**
